steps:
# Install dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']

# Build shared packages
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build', '--workspace=types']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build', '--workspace=ui']

# Build and push web container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/digital-agency-web:$COMMIT_SHA', '-f', 'apps/web/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/digital-agency-web:$COMMIT_SHA']

# Build and push API container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/digital-agency-api:$COMMIT_SHA', '-f', 'apps/api/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/digital-agency-api:$COMMIT_SHA']

# Update the web deployment
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/digital-agency-web'
  - 'web=gcr.io/$PROJECT_ID/digital-agency-web:$COMMIT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'  # replace with your GKE cluster zone
  - 'CLOUDSDK_CONTAINER_CLUSTER=digital-agency-cluster'  # replace with your cluster name

# Update the API deployment
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/digital-agency-api'
  - 'api=gcr.io/$PROJECT_ID/digital-agency-api:$COMMIT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'  # replace with your GKE cluster zone
  - 'CLOUDSDK_CONTAINER_CLUSTER=digital-agency-cluster'  # replace with your cluster name

# Tag the images as latest
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/digital-agency-web:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/digital-agency-web:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/digital-agency-api:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/digital-agency-api:latest']

# Push the latest tags
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/digital-agency-web:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/digital-agency-api:latest']

images:
- 'gcr.io/$PROJECT_ID/digital-agency-web:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/digital-agency-web:latest'
- 'gcr.io/$PROJECT_ID/digital-agency-api:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/digital-agency-api:latest'

timeout: 1800s