apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app: digital-agency
  environment: production

# You can define environment-specific configurations
# by creating overlays in separate directories
# For example:
# - overlays/dev/
# - overlays/staging/
# - overlays/production/