apiVersion: v1
kind: Service
metadata:
  name: digital-agency-web-service
  labels:
    app: digital-agency
    component: web
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: digital-agency
    component: web
---
apiVersion: v1
kind: Service
metadata:
  name: digital-agency-api-service
  labels:
    app: digital-agency
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: digital-agency
    component: api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digital-agency-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    # Optional: Add SSL with managed certificates
    # networking.gke.io/managed-certificates: "digital-agency-cert"
    # Optional: Configure CDN
    # kubernetes.io/ingress.global-static-ip-name: "digital-agency-ip"
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: digital-agency-web-service
            port:
              number: 80
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: digital-agency-api-service
            port:
              number: 4000